version: '3'
services:
  hivemq:
    build: hivemq
    restart: always
    ports:
      - 1883:1883
      - 8080:8080
      - 8000:8000
  zookeeper:
    image: bitnami/zookeeper:latest
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    volumes:
      - ./zookeeper/data:/bitnami/zookeeper
  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    restart: always
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      # see https://rmoff.net/2018/08/02/kafka-listeners-explained/
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    volumes:
      - ./kafka/data:/bitnami/kafka
  apache:
    image: bitnami/apache:2.4
    ports:
      - 8888:8080
    volumes:
      - ./apache/influxdb_proxy.conf:/vhosts/influxdb_proxy.conf:ro
  mqtt2kafkabridge:
    image: marmaechler/mqtt2kafkabridge:1.0.0
    depends_on:
      - kafka
      - hivemq
    restart: always
    environment:
      KAFKA_BROKER_HOST: kafka:9092
      MQTT_BROKER_HOST: hivemq:1883
      MQTT_AUTOMATIC_RECONNECT: 'true'
    volumes:
      - ./mqtt2kafkabridge/logs:/opt/mqtt2kafkabridge/logs
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    restart: always
    volumes:
      - ./influxdb/data:/var/lib/influxdb
